### ISSUE TITLE
SAMD51 Thing Plus Bootloader cannot load code larger than 496k

### ISSUE THREAD

**Issue by robert-hh** [sparkfun/SAMD51_Thing_Plus#4]
The bootloader seems to refuse loading code in address ranges >= 0x80000. If the binary size of the code exceeds 496k (=512k - 16k), the loading address exceeds 0x80000 and the code will not run. The code can be loaded successfully using a JLink adapter, so it's not a problem of the MCU, not being able to run code from that address space.

I verified that using the Ozone debugger and a JLink adapter by modifying the addresses 0x80000 - 0x80003, which should be overwritten by the Bootloader when loading code. That did not happen. Loading code using the JLink adapter set these addresses to the proper value.

Is that problem known, and is there a fix for it, like an updated bootloader?

**Comment by robert-hh** [comment]
It seems that with the firmware supplied in PR #2 the problem is gone. The board I tested had bootloader v2.0.0-34, dated Mar 20, 2019.

**Comment by rrainey** [comment]
Where is the code for the SAMD51 Thing Plus uf2 bootloader, anyway?  I expected to find it in https://github.com/microsoft/uf2-samdx1 however I don't see a board definition there -- somewhere else?

**Comment by robert-hh** [comment]
There are board definition files in the referenced PR at https://github.com/sparkfun/SAMD51_Thing_Plus/pull/2/commits/4b5b61ea15a099e99139af206e16e3b233d59143

**Comment by edspark** [comment]
This issue can be closed as the aforementioned PR has now been pulled in.
